name: Skyblock
version: '0.0.0'
main: com.partlysunny.Skyblock
api-version: 1.17
authors: [ PartlySunny ]
depend: [ Citizens, NBTAPI, SidebarAPI, WorldEdit ]
description: Hypixel Skyblock Remade
commands:
  sbgive:
    description: Gives an skyblock item
    usage: /sbgive <item-id>
    permission: skyblock.op
  sbsummon:
    description: Summons a skyblock entity
    usage: /sbsummon <entity-id>
    permission: skyblock.op
  sbadd:
    description: Adds an addition to your held item
    usage: /sbadd <addition-id>
    permission: skyblock.op
  sbreforge:
    description: Adds a reforge to your held item
    usage: /sbreforge <reforge-id>
    permission: skyblock.op
  sbstar:
    description: Adds a amount of stars to your held item (default 5)
    usage: /sbstar [optional-amount]
    permission: skyblock.op
  sbfrag:
    description: Sets your held item to fragged / unfragged (default true)
    usage: /sbfrag [optional-boolean]
    permission: skyblock.op
  sbenchant:
    description: Adds and enchant to your held item (default 1)
    usage: /sbenchant <enchant-id> [level]
    permission: skyblock.op
  craft:
    description: Opens the craft menu
    usage: /craft
    permission: skyblock.user
permissions:
  skyblock.op:
    description: Gives you access to commands like sbgive and sbsummon
    default: op
  skyblock.user:
    description: default user
    default: true
